name: Run Ruby Script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-ruby-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Ruby Script
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Execute Script
      env:
        API_KEY: ${{ secrets.SLACK_BOT_TOKEN }}
      run: |
        ruby hello.rb
